services:
  mysql:
    image: mysql:8.0
    container_name: talkmaster-mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: talkmaster_db
      MYSQL_USER: talkmaster_user
      MYSQL_PASSWORD: talkmaster_password
    ports:
      - "3306:3306"
    volumes:
      - mysql-talkmaster-data:/var/lib/mysql
    networks:
      - talkmaster-network
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: talkmaster-phpmyadmin
    platform: linux/amd64 
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      UPLOAD_LIMIT: 1G
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - talkmaster-network
    restart: unless-stopped

networks:
  talkmaster-network:
    driver: bridge

volumes:
  mysql-talkmaster-data:
